CREATE DATABASE TCC_HOMM3EI_F4IFTH;
USE TCC_HOMM3EI_F4IFTH;

CREATE TABLE USUARIO(
    ID_USUARIO           INT     PRIMARY KEY  IDENTITY (1,1),
    NOME         VARCHAR          (35),
    SOBRENOME    VARCHAR          (50),
    SENHA        VARCHAR       (20),
    EMAIL        VARCHAR       (64),
    TELEFONE     NUMERIC        (9),
    CPF          NUMERIC        (11),
    ENDERECO     VARCHAR        (55),
    N_RESIDENCIAL NUMERIC        (5),
    BAIRRO        VARCHAR          (20), 
    COMPLEMENTORESI VARCHAR     (15),
    CEP NUMERIC(8),
    ID_CADASTRO      NUMERIC (10),
    CONF_SENHA       VARCHAR (20)
);

CREATE TABLE PRESTADOR(
    ID_PRESTADOR INT PRIMARY KEY IDENTITY (1, 1),
    CATEGORIA_SERVICO        VARCHAR     (35),
    NOME_COMERCIAL           VARCHAR   (80),
    CNPJ                     NUMERIC   (14)
);


CREATE TABLE AGENDAMENTO(
    ID_AGENDAMENTO INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
    HR_AGENDAMENTO     TIME NOT NULL, 
    VL_ORC             NUMERIC          (18, 2) NOT NULL,
    DT_AGENDAMENTO     DATETIME NOT NULL
);

CREATE TABLE PEDIDO(
    ID_PEDIDO INT PRIMARY KEY IDENTITY (1,1),
    STATUS_SERVICO      VARCHAR      (20) NOT NULL,
    CATEGORIA_PEDIDO    VARCHAR   (20) NOT NULL,
    DESCRICAO_PEDIDO    VARCHAR   (90) NOT NULL,
    ID_AGENDAMENTO      INT NOT NULL,
    ID_PRESTADOR        INT NOT NULL,
    ID_CLIENTE          INT NOT NULL,
    FOREIGN KEY (ID_AGENDAMENTO) REFERENCES AGENDAMENTO (ID_AGENDAMENTO),
    FOREIGN KEY (ID_PRESTADOR) REFERENCES PRESTADOR (ID_PRESTADOR),

);

CREATE TABLE CATEGORIA(
    ID_CATEGORIA INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
    NOME_CATEGORIA VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE SERVICO(   
    ID_SERV INT PRIMARY KEY IDENTITY NOT NULL,
    NOME_SERVICO        VARCHAR    (45),
    DESCRICAO_SERVICO   VARCHAR (60),
    ID_PRESTADOR       INT NOT NULL,
    ID_CATEGORIA      INT NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA),
    FOREIGN KEY (ID_PRESTADOR) REFERENCES PRESTADOR (ID_PRESTADOR)
);

CREATE TABLE REL_PRESTADOR_SERVICO(
    ID_SERV        INT,
    ID_PRESTADOR   INT,
    FOREIGN KEY (ID_SERV) REFERENCES SERVICO (ID_SERV),
    FOREIGN KEY (ID_PRESTADOR) REFERENCES PRESTADOR (ID_PRESTADOR)
);

CREATE TABLE AGENDA(
    ID_AGENDA INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
    HR_DISPONIVEL     TIME NOT NULL,
    HR_INDISPONIVEL   TIME NOT NULL,
    DIA_SERV          DATE NOT NULL,
    ID_PRESTADOR      INT NOT NULL,
    FOREIGN KEY (ID_PRESTADOR) REFERENCES PRESTADOR (ID_PRESTADOR)
);

CREATE TABLE DATA_AGENDA (
   ID_DTAGENDA INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
   DT_SERV       DATE NOT NULL,
   HR_SERV       TIME NOT NULL
);

CREATE TABLE AVALIACAO (
    ID_AVALIACAO      INT PRIMARY KEY IDENTITY (1,1),
    ID_PEDIDO         INT NOT NULL,
    COMENTARIOS       VARCHAR(200),
    NOTA              INT NOT NULL,
    DT_AVALIACAO      DATE NOT NULL,
    ID_PRESTADOR      INT NOT NULL,
    FOREIGN KEY (ID_PRESTADOR) REFERENCES PRESTADOR (ID_PRESTADOR),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
);

CREATE TABLE PAGAMENTO(
	 ID_PGTO       INT            NOT NULL  PRIMARY KEY IDENTITY (1,1),
	 VALOR_TAXA    NUMERIC (7,2)  NOT NULL,
	 FORMA_PGTO    INT            NOT NULL,
);

CREATE TABLE CONTRATO(
	 ID_CONTRATO    INT            NOT NULL  PRIMARY KEY IDENTITY (1,1),
	 ID_PGTO        INT            NOT NULL,
	 ID_PRESTADOR   INT            NOT NULL  FOREIGN KEY (ID_PRESTADOR) REFERENCES PRESTADOR (ID_PRESTADOR) ,
	 PER_TAXA       NUMERIC (3,2)  NOT NULL,
	 FOREIGN KEY (ID_PGTO) REFERENCES PAGAMENTO (ID_PGTO) ,

);

 CREATE TABLE POSTAGEM(
 ID_POSTAGEM INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
 URL             TEXT NOT NULL,
 DESCRICAO_POST  TEXT,
 RESOLUCAO       VARCHAR  (20),
 TAMANHO_ARQUIVO DECIMAL  (10, 2),
 TIPO_ARQUIVO    VARCHAR     (10),
 DT_POSTAGEM     DATE NOT  NULL 
 );